### PR TITLE
Add React Composer

### PR DESCRIPTION
**Pull request by jamesplease**
:wave:

This is a library I wrote to help out with the new Context API (as well as any other render prop components that a developer might want to compose together).

It was mentioned in [Kent Dodd's article on Context](https://medium.com/dailyjs/reacts-%EF%B8%8F-new-context-api-70c9fe01596b) that is already included on this list, and can be seen in action in [this Context example](https://codesandbox.io/s/92pj14134y), also from Kent.

Because this isn't _explicitly_ for context, and is more just a useful utility, you might not think that it fits in the list. No worries if so. I just figured I would PR it in case you thought it was a good fit.

Thanks for reading! :v:

### CODE REVIEW

**Comment by diegohaz** [comment]
Hey, @jamesplease. Thank you for the library.

Could you please change the description to be more focused on context? I mean, people coming here and have a first look to React Context may not easily relate "render prop" to it.

**Comment by jamesplease** [comment]
@diegohaz , I've updated the description. What do you think?

**Comment by diegohaz** [comment]
Looks good.  😊
Thank you.

**Comment by jamesplease** [comment]
Thanks @diegohaz :v:

**Pull request merged**
